global class AcqCSVResponseHandler {
    public String EnteraID {get; set;}
 	public String APN {get; set;}
    public String Bid_Type {get; set;}
    public String Bulk_Deal {get; set;}
    public String Property_Street_Address {get; set;}
    public String Property_City {get; set;}
    public String Property_State {get; set;}
    public String Property_Zip_Code {get; set;}
    public String County {get; set;}
    public String Property_Type {get; set;}
    public String Year_Built {get; set;}
    public String Bedrooms {get; set;}
	public String Baths {get; set;}
    public String Square_Feet {get; set;}
    public String Pool {get; set;}
    public String Parking {get; set;}
    public String Roof_Type {get; set;}
   // public String oppStatus {get; set;}
    public String HVAC_Type {get; set;}
    public String Lot_Sq_Ft {get; set;}
    public String HOA {get; set;}
    public String HOA_Name {get; set;}
    public String Property_Fits_Buy_Box {get; set;}
    public String Property_Details_Validated {get; set;}
   // public String prosStatus {get; set;}
    public String Market_Value {get; set;}
    public String Initial_Rehab_Bud_Est {get; set;}
    public String Exp_Gross_Mon_Rent {get; set;}
    public String RPC_Structure_Qual {get; set;}
    public String RPC_Stru_PSF {get; set;}
    public String RPC_Land_Value {get; set;}
    public String Previous_High_Value {get; set;}
    public String Previous_High_Value_Date {get;set;}
    public String Property_Tax_Est {get; set;}
    public String Monthly_HOA {get; set;}
    public String Closing_Title_Acq_Cost_Est {get; set;}
    public String Offer_Price_Max_Bid {get; set;}
    public String Latitude{get;set;}
    public String Longitude{get; set;}
    
}